name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bubkoo/release-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
